-   repo: https://github.com/pre-commit/pre-commit-hooks
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: check-symlink
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: flake8
        args: [--max-complexity 10]
 
-   repo: https://github.com/pre-commit/pre-commit
    hooks:
    -   id: validate_config
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
-   repo: https://github.com/pre-commit/mirrors-csslint
    hooks:
    -   id: csslint
-   repo: https://github.com/pre-commit/mirrors-jshint
    hooks:
    -   id: jshint
