-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.5.1
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: flake8
        args: [--max-complexity 10]

-   repo: https://github.com/pre-commit/pre-commit
    sha: v0.8.2
    hooks:
    -   id: validate_config
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.2.0
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
-   repo: https://github.com/pre-commit/mirrors-csslint
    sha: 9c492bd1cc4446a207ecd1d98784be436de565de
    hooks:
    -   id: csslint
-   repo: https://github.com/pre-commit/mirrors-jshint
    sha: v2.9.2
    hooks:
    -   id: jshint
